platform :ios, '8.0'
use_frameworks!

target 'SDWebImageBPGCoder_Example' do
  pod 'SDWebImageBPGCoder', :path => '../'

  target 'SDWebImageBPGCoder_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
