platform :ios, '9.0'
use_frameworks!

target 'SDWebImageBPGCoder_Example' do
  pod 'SDWebImageBPGCoder', :path => '../', :subspecs => [
  	'libbpg',
  	'bpgenc'
  ]

  target 'SDWebImageBPGCoder_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
