language: objective-c
osx_image: xcode9.4

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

addons:
  ssh_known_hosts: github.com

notifications:
  email: false

before_install:
  - env
  - locale
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod --version
  - pod setup --silent > /dev/null
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - set -o pipefail

  - echo Check if the library described by the podspec can be built
  - pod lib lint --allow-warnings

  - echo Build example
  - pod install --project-directory=Example
  - xcodebuild build -workspace Example/SDWebImageBPGCoder.xcworkspace -scheme SDWebImageBPGCoder-Example -sdk iphonesimulator -destination 'name=iPhone 6s' -configuration Debug | xcpretty -c
